DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/camera-kernel
KBUILD_DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/camera-kernel

dtbo-$(CONFIG_ARCH_CAPE) += ../cape-camera.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += ../ukee-camera.dtbo
dtbo-$(CONFIG_ARCH_DIWALI) += ../diwali-camera.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += ../waipio-camera.dtbo

dtbo-$(CONFIG_ARCH_CAPE) += jennie_21605-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += udon_22803-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += jennie_21606-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += ovaltine-21841-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += senna-22624-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += senna-22625-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += whiteswan_22001-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += lvzhou_22015-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += monroe_22091-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += monroe_22091-camera-cape-overlay-preT0.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += daoxiang_23023-camera-cape-overlay.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += daoxiang_23023-camera-cape-overlay-T1.dtbo
dtbo-$(CONFIG_ARCH_CAPE) += senna_22623-camera-ukee-overlay.dtbo

dtbo-$(CONFIG_ARCH_DIWALI) += wuyi-21125-camera-diwali-overlay.dtbo

dtbo-$(CONFIG_ARCH_WAIPIO) += wly-20846-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += wly-20846-camera-waipio-overlay-EVB.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += wly-20846-camera-waipio-overlay-preT0.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += mt-20845-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += jnc-20865-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += baize-21001-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += ferrari-21631-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += kunpeng-21009-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += unicorn-21166-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += jennie_21605-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += udon_22803-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += jennie_21606-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += monroe_22091-camera-waipio-overlay.dtbo
dtbo-$(CONFIG_ARCH_WAIPIO) += monroe_22091-camera-waipio-overlay-preT0.dtbo

always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
