ifeq ($(CONFIG_BUILD_ARM64_DT_OVERLAY), y)

DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/camera-kernel

#include $(srctree)/$(src)/config/parrot.mk
include $(srctree)/$(src)/config/waipio.mk

#PLUS_DTS_OVERLAY start
dtbo-$(CONFIG_ARCH_WAIPIO) += oplus/ferrari-21631-camera-waipio-overlay.dtbo

#OPLUS_DTS_OVERLAY end

else
$(error CONFIG_BUILD_ARM64_DT_OVERLAY is: $(CONFIG_BUILD_ARM64_DT_OVERLAY))
endif

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
